[msbuild]
project = "DotTerritory/DotTerritory.csproj"
artifacts_folder = ".artifacts"
configuration = "Release"

[msbuild.properties]
PublishTrimmed = false
PublishSingleFile = false
PublishReadyToRun = false
SelfContained = false

[github]
user = "danfma"
repo = "DotTerritory"

